service: serverless-function-example

provider:
    name: aws
    runtime: nodejs16.x

functions:
    hello:
        handler: handler.hello
        events:
            - http:
                  path: hello
                  method: get
